export const UI_START_LOADING = "UI_START_LOADING0;";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN = "LOGIN";
export const FETCH_ALL_FAMILY_TASKS = "FETCH_ALL_FAMILY_TASKS";
export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";
export const FETCH_FAMILY_MEMBERS = "FETCH_FAMILY_MEMBERS";
